name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        cd ./studentapp-main
        docker-compose up --build --file Dockerfile
      
    - name: Build and push docker image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: tony06/student-app
        registry: docker.io
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
