name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: docker login
      env:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Build the Docker Image
      run: docker build . --file Dockerfile --tag chamodshehanka/node-test:$(date +%s)

    - name: Docker Push
      run: docker push ${{secrets.DOCKER_USERNAME}}/tony06/student-app
